
services:
  postgres:
    image: postgres:15-alpine
    container_name: orbnoc-db
    environment:
      POSTGRES_DB: orbnoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9857Dudu
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orbnoc-network

  redis:
    image: redis:7-alpine
    container_name: orbnoc-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - orbnoc-network

volumes:
  postgres_data:
  redis_data:

networks:
  orbnoc-network:
    driver: bridge