"""schema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 21:03:17.473334
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role in ('admin','user')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_access_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_logs'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('check_type', sa.String(length=10), server_default='icmp', nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), server_default='10', nullable=False),
    sa.Column('failure_threshold', sa.Integer(), server_default='3', nullable=False),
    sa.Column('sla_threshold_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='unknown', nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sla_breached', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('avg_latency', sa.Float(), nullable=True),
    sa.Column('min_latency', sa.Float(), nullable=True),
    sa.Column('max_latency', sa.Float(), nullable=True),
    sa.Column('jitter', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("check_type in ('icmp','tcp')", name=op.f('ck_devices_check_type')),
    sa.CheckConstraint("status in ('unknown','online','offline')", name=op.f('ck_devices_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('user_id', 'ip', name='uq_devices_user_ip')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_channels_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels')),
    sa.UniqueConstraint('user_id', 'kind', name='uq_notification_channels_user_kind')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity in ('success','warning','error','info')", name=op.f('ck_events_severity')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_events_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_user_created', 'events', ['user_id', 'created_at'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('jitter', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_metrics_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics'))
    )
    op.create_index('ix_metrics_device_recorded', 'metrics', ['device_id', 'recorded_at'], unique=False)
    op.create_index('ix_metrics_recorded_at', 'metrics', ['recorded_at'], unique=False)
    op.create_table('metrics_hourly',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('ok_samples', sa.Integer(), nullable=False),
    sa.Column('avg_latency', sa.Float(), nullable=True),
    sa.Column('min_latency', sa.Float(), nullable=True),
    sa.Column('max_latency', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_metrics_hourly_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'hour', name=op.f('pk_metrics_hourly'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics_hourly')
    op.drop_index('ix_metrics_recorded_at', table_name='metrics')
    op.drop_index('ix_metrics_device_recorded', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_events_user_created', table_name='events')
    op.drop_table('events')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('access_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
